services:
  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    depends_on:
      - django_app

  django_app:
    build:
      context: ./my_django_project_final
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./my_django_project_final:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
